spring.application.name=bankapp
app.jwt.secret=local-development-secret-key-change-this-before-deployment-123456
app.jwt.expiration-ms=3600000

spring.mongodb.uri=mongodb+srv://database-access:rPXfC5CKggwpm36W@simple-bank-app.u6euw4s.mongodb.net/bankapp?appName=simple-bank-app
spring.data.mongodb.uri=spring.data.mongodb.uri=mongodb+srv://database-access:rPXfC5CKggwpm36W@simple-bank-app.u6euw4s.mongodb.net/bankapp?appName=simple-bank-app

app.admin.username=${ADMIN_USERNAME:}
app.admin.password=${ADMIN_PASSWORD:}
